apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ashinjoy22@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: drivee-tls
  namespace: default
spec:
  secretName: drivee-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: drivee.online
  dnsNames:
    - drivee.online